# Generated by Django 5.0.6 on 2026-03-14 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0003_remove_licensekey_db_quota_mb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PembelianLisensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(max_length=50, unique=True, verbose_name='Nomor Transaksi')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Pembelian')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Dikonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Harga')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('klien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.client', verbose_name='Klien')),
            ],
            options={
                'verbose_name': 'Pembelian Lisensi',
                'verbose_name_plural': 'Pembelian Lisensi',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PembelianLisensiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah Lisensi')),
                ('durasi_hari', models.PositiveIntegerField(default=365, verbose_name='Durasi (Hari)')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pembelian.pembelianlisensi', verbose_name='Pembelian')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Item Pembelian',
                'verbose_name_plural': 'Item Pembelian',
            },
        ),
    ]
