# Generated by Django 5.0.6 on 2026-03-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default='Central License Server', max_length=200, verbose_name='Nama Perusahaan')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=50, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pengaturan/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='pengaturan/', verbose_name='Favicon')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Perusahaan')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, max_length=200, verbose_name='SMTP User')),
                ('smtp_password', models.CharField(blank=True, max_length=200, verbose_name='SMTP Password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Gunakan TLS')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode Maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='Sistem sedang dalam maintenance.', verbose_name='Pesan Maintenance')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Perusahaan',
                'verbose_name_plural': 'Pengaturan Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='TemplateCetak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('lisensi', 'Sertifikat Lisensi'), ('invoice', 'Invoice Pembelian'), ('laporan', 'Laporan')], max_length=30, verbose_name='Jenis Template')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('header_nama_perusahaan', models.CharField(blank=True, max_length=200, verbose_name='Header - Nama Perusahaan')),
                ('header_alamat', models.CharField(blank=True, max_length=300, verbose_name='Header - Alamat')),
                ('header_telepon', models.CharField(blank=True, max_length=50, verbose_name='Header - Telepon')),
                ('header_email', models.CharField(blank=True, max_length=200, verbose_name='Header - Email')),
                ('header_website', models.CharField(blank=True, max_length=200, verbose_name='Header - Website')),
                ('footer_copyright', models.CharField(blank=True, max_length=300, verbose_name='Footer Copyright')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Cetak',
                'verbose_name_plural': 'Template Cetak',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore'), ('reset', 'Reset')], max_length=10, verbose_name='Aksi')),
                ('nama_file', models.CharField(blank=True, max_length=200, verbose_name='Nama File')),
                ('ukuran_file', models.BigIntegerField(default=0, verbose_name='Ukuran File (bytes)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riwayat Backup',
                'verbose_name_plural': 'Riwayat Backup',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
