# Generated by Django 5.0.6 on 2026-03-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='smtp_user',
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_footer',
            field=models.TextField(blank=True, verbose_name='Email Footer'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_header',
            field=models.TextField(blank=True, verbose_name='Email Header'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP User'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Gunakan TLS'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='forgot_password_message',
            field=models.TextField(blank=True, verbose_name='Pesan Forgot Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='forgot_password_subject',
            field=models.CharField(blank=True, default='Reset Password Anda', max_length=200, verbose_name='Subjek Forgot Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='pajak_default',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Default Pajak (%)'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='register_message',
            field=models.TextField(blank=True, verbose_name='Pesan Register'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='register_subject',
            field=models.CharField(blank=True, default='Verifikasi Email Anda', max_length=200, verbose_name='Subjek Register'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_description',
            field=models.TextField(blank=True, verbose_name='Deskripsi Sistem'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/', verbose_name='Favicon Sistem'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Keywords (SEO)'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pengaturan/', verbose_name='Logo Sistem'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_title',
            field=models.CharField(blank=True, default='Central License Server', max_length=200, verbose_name='Judul Sistem'),
        ),
    ]
