# Generated by Django 5.0.6 on 2026-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0002_remove_pengaturanperusahaan_smtp_host_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecetak',
            options={'ordering': ['jenis'], 'verbose_name': 'Template Cetak', 'verbose_name_plural': 'Template Cetak'},
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='footer_keterangan',
            field=models.CharField(blank=True, default='Dokumen ini dicetak secara otomatis.', max_length=200, verbose_name='Keterangan Footer'),
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='footer_ucapan',
            field=models.CharField(blank=True, default='Terima kasih atas kepercayaan Anda!', max_length=200, verbose_name='Ucapan Terima Kasih'),
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='signature_kanan_label',
            field=models.CharField(blank=True, default='Dibuat Oleh', max_length=50, verbose_name='Label Tanda Tangan Kanan'),
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='signature_kiri_label',
            field=models.CharField(blank=True, default='Disetujui Oleh', max_length=50, verbose_name='Label Tanda Tangan Kiri'),
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='tampilkan_logo',
            field=models.BooleanField(default=True, verbose_name='Tampilkan Logo'),
        ),
        migrations.AddField(
            model_name='templatecetak',
            name='tampilkan_website',
            field=models.BooleanField(default=False, verbose_name='Tampilkan Website'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 Central License Server', max_length=300, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_alamat',
            field=models.TextField(blank=True, default='Jl. Contoh Alamat No. 123', verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_email',
            field=models.EmailField(blank=True, default='info@cls.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_nama_perusahaan',
            field=models.CharField(default='Central License Server', max_length=200, verbose_name='Nama Perusahaan'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_telepon',
            field=models.CharField(blank=True, default='(021) 1234-5678', max_length=50, verbose_name='Telepon'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('lisensi', 'Sertifikat Lisensi'), ('invoice', 'Invoice Pembelian'), ('laporan', 'Laporan'), ('export_excel', 'Template Export Excel'), ('export_pdf', 'Template Export PDF')], max_length=30, unique=True, verbose_name='Jenis Template'),
        ),
    ]
