# Generated by Django 6.0.3 on 2026-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0003_alter_templatecetak_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='nama_perusahaan',
            field=models.CharField(default='SINTSGROUP', max_length=200, verbose_name='Nama Perusahaan'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='system_title',
            field=models.CharField(blank=True, default='SINTSGROUP License Server', max_length=200, verbose_name='Judul Sistem'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 SINTSGROUP', max_length=300, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_nama_perusahaan',
            field=models.CharField(default='SINTSGROUP', max_length=200, verbose_name='Nama Perusahaan'),
        ),
    ]
