# Generated by Django 6.0.3 on 2026-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0004_alter_pengaturanperusahaan_nama_perusahaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecetak',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo perusahaan. Kosongkan untuk menggunakan logo default.', null=True, upload_to='template_cetak/', verbose_name='Logo Perusahaan'),
        ),
    ]
