# Generated by Django 5.0.6 on 2026-03-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Klien / Perusahaan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Klien',
                'verbose_name_plural': 'Klien',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Produk')),
                ('code', models.CharField(help_text='Contoh: ERP, SIMKOS', max_length=20, unique=True, verbose_name='Kode Produk')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Otomatis digenerate atau masukkan manual', max_length=50, unique=True, verbose_name='Kunci Lisensi')),
                ('registered_domain', models.CharField(blank=True, help_text='Domain tempat lisensi ini diaktifkan (contoh: pt-abadi.erpserver.com)', max_length=255, null=True, verbose_name='Domain Terdaftar')),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='Berapa lama lisensi ini berlaku sejak diaktifkan', verbose_name='Durasi (Hari)')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('suspended', 'Ditangguhkan / Diblokir'), ('expired', 'Kadaluarsa')], default='active', max_length=20, verbose_name='Status Lisensi')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Sudah Diaktifkan?')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Aktivasi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Kadaluarsa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.client', verbose_name='Klien')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licenses.product', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Kunci Lisensi',
                'verbose_name_plural': 'Kunci Lisensi',
            },
        ),
    ]
