# Generated by Django 5.0.6 on 2026-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='db_quota_mb',
            field=models.PositiveIntegerField(default=1024, help_text='Batas maksimal ukuran database yang diizinkan untuk lisensi klien ini (Default 1GB = 1024MB)', verbose_name='Kuota Database (MB)'),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='db_usage_mb',
            field=models.FloatField(default=0.0, verbose_name='Penggunaan Database Saat Ini (MB)'),
        ),
    ]
