# Generated by Django 5.0.6 on 2026-03-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_licensekey_db_quota_mb_licensekey_db_usage_mb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='db_quota_mb',
        ),
        migrations.RemoveField(
            model_name='licensekey',
            name='db_usage_mb',
        ),
    ]
