# Generated by Django 5.0.6 on 2026-03-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_remove_licensekey_db_quota_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='max_devices',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah maksimal perangkat yang boleh terikat pada lisensi ini', verbose_name='Maks Perangkat'),
        ),
        migrations.CreateModel(
            name='LicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate', 'Aktivasi'), ('validate', 'Validasi'), ('deactivate', 'Deaktivasi'), ('suspend', 'Suspend'), ('renew', 'Perpanjangan'), ('bind_device', 'Bind Perangkat'), ('unbind_device', 'Unbind Perangkat'), ('expired', 'Kadaluarsa')], max_length=30, verbose_name='Aksi')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('hardware_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hardware ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='licenses.licensekey', verbose_name='Kunci Lisensi')),
            ],
            options={
                'verbose_name': 'Log Lisensi',
                'verbose_name_plural': 'Log Lisensi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(help_text='ID unik perangkat (MAC Address hash, Android ID, dll)', max_length=255, verbose_name='Hardware ID')),
                ('device_name', models.CharField(blank=True, help_text='Contoh: Samsung Galaxy A52, VPS-Server-01', max_length=255, null=True, verbose_name='Nama Perangkat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain/URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Pertama Terlihat')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Terakhir Terlihat')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bindings', to='licenses.licensekey', verbose_name='Kunci Lisensi')),
            ],
            options={
                'verbose_name': 'Perangkat Terikat',
                'verbose_name_plural': 'Perangkat Terikat',
                'ordering': ['-last_seen'],
                'unique_together': {('license', 'hardware_id')},
            },
        ),
    ]
