# Generated by Django 5.0.6 on 2026-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('properti', 'Properti'), ('penyewa', 'Penyewa'), ('sewa', 'Sewa'), ('biaya', 'Biaya'), ('hr', 'Karyawan KOS'), ('laporan', 'Laporan'), ('automation', 'Automasi Telegram'), ('user_management', 'Manajemen User'), ('access_control', 'Access Control'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('ai', 'AI Assistant')], max_length=50, verbose_name='Module'),
        ),
    ]
