# Generated by Django 5.0.6 on 2026-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('licenses', 'Manajemen Lisensi'), ('user_management', 'Manajemen User'), ('access_control', 'Access Control')], max_length=50, verbose_name='Module'),
        ),
    ]
