# Generated by Django 5.0.6 on 2026-03-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('licenses', 'Manajemen Lisensi'), ('pembelian', 'Pembelian Lisensi'), ('laporan', 'Laporan'), ('ai', 'AI Manajemen'), ('user_management', 'Manajemen User'), ('access_control', 'Access Control'), ('activity_log', 'Log Aktivitas'), ('automation', 'Telegram'), ('pengaturan', 'Pengaturan')], max_length=50, verbose_name='Module'),
        ),
    ]
