# Generated by Django 5.0.6 on 2026-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('aktivasi', 'Aktivasi Lisensi'), ('kadaluarsa', 'Kadaluarsa Lisensi'), ('pembelian', 'Pembelian Lisensi'), ('suspend', 'Suspend Lisensi')], max_length=30, verbose_name='Jenis Event')),
                ('nomor_referensi', models.CharField(max_length=100, verbose_name='Nomor Referensi')),
                ('pesan', models.TextField(verbose_name='Pesan yang Dikirim')),
                ('status', models.CharField(choices=[('sukses', 'Sukses'), ('gagal', 'Gagal')], max_length=10, verbose_name='Status')),
                ('respons', models.TextField(blank=True, null=True, verbose_name='Respons API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error')),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim Pada')),
            ],
            options={
                'verbose_name': 'Log Notifikasi',
                'verbose_name_plural': 'Log Notifikasi',
                'ordering': ['-dikirim_pada'],
            },
        ),
        migrations.CreateModel(
            name='PengaturanTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Token dari @BotFather', max_length=200, verbose_name='Bot Token')),
                ('chat_id', models.CharField(blank=True, help_text='Chat ID tujuan (grup atau personal)', max_length=100, verbose_name='Chat ID')),
                ('aktif', models.BooleanField(default=False, verbose_name='Aktif')),
                ('notif_aktivasi', models.BooleanField(default=True, verbose_name='Notifikasi Aktivasi Lisensi')),
                ('notif_kadaluarsa', models.BooleanField(default=True, verbose_name='Notifikasi Kadaluarsa Lisensi')),
                ('notif_pembelian', models.BooleanField(default=True, verbose_name='Notifikasi Pembelian Lisensi')),
                ('notif_suspend', models.BooleanField(default=True, verbose_name='Notifikasi Suspend Lisensi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Telegram',
                'verbose_name_plural': 'Pengaturan Telegram',
            },
        ),
        migrations.CreateModel(
            name='TemplatePesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('aktivasi', 'Aktivasi Lisensi'), ('kadaluarsa', 'Kadaluarsa Lisensi'), ('pembelian', 'Pembelian Lisensi'), ('suspend', 'Suspend Lisensi')], max_length=30, unique=True, verbose_name='Jenis Event')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('template_pesan', models.TextField(help_text='Gunakan variabel {{variabel}} untuk placeholder', verbose_name='Template Pesan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Pesan',
                'verbose_name_plural': 'Template Pesan',
                'ordering': ['jenis'],
            },
        ),
    ]
