# Generated by Django 5.0.6 on 2026-03-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('activate', 'Aktivasi Lisensi'), ('suspend', 'Suspend Lisensi'), ('view', 'View')], max_length=20, verbose_name='Aksi')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Object Repr')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Perubahan (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Request Path')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP Method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Aktivitas User',
                'verbose_name_plural': 'Aktivitas User',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_e92581_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b44d49_idx'), models.Index(fields=['action'], name='activity_lo_action_120b23_idx')],
            },
        ),
    ]
