# Generated by Django 5.0.6 on 2026-03-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (GPT)'), ('groq', 'Groq (Llama)')], default='gemini', max_length=20, verbose_name='AI Provider')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('model_name', models.CharField(blank=True, default='gemini-2.0-flash', max_length=100, verbose_name='Model Name')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('system_prompt', models.TextField(blank=True, default='Kamu adalah AI Assistant untuk Central License Server — sistem manajemen lisensi software. Tugasmu membantu admin mengelola lisensi produk, data klien, analisa bisnis lisensi, dan memberikan insight tentang performa penjualan lisensi. Jawab dalam Bahasa Indonesia yang profesional.', verbose_name='System Prompt')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi AI',
                'verbose_name_plural': 'Konfigurasi AI',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, verbose_name='Role')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('intent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intent Terdeteksi')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='Provider')),
                ('model_used', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens')),
                ('response_time', models.FloatField(default=0, verbose_name='Waktu Respon (detik)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riwayat Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Buruk'), (2, 'Kurang'), (3, 'Cukup'), (4, 'Baik'), (5, 'Sangat Baik')], verbose_name='Rating')),
                ('komentar', models.TextField(blank=True, verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_assistant.chathistory', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Feedback Chat',
                'verbose_name_plural': 'Feedback Chat',
            },
        ),
    ]
